package: &package br.com.bbatistadaniel
name: fro3
description: "Flutter Rule of 3 Calculator"
publish_to: 'none'
version: &version 1.0.1.0

environment:
  sdk: ^3.12.1

dependencies:
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  number_text_input_formatter: ^1.0.0+9
  rename: ^3.1.0
  share_plus: ^13.1.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.17.0

flutter:
  uses-material-design: true
  generate: true

msix_config:
  display_name: FRO3
  publisher_display_name: "Daniel Batista Bueno"
  identity_name: *package
  msix_version: *version
  logo_path: assets\icon.png
  execution_alias: fro3
  languages: en-us, en-uk, pt-br, pt-pt